// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEQZOvRWsbHfo0Ru2rgWk5I7jZKh0HxY',
    appId: '1:825501161515:web:64d789189bf0505c59f26e',
    messagingSenderId: '825501161515',
    projectId: 'basicapp-85fbc',
    authDomain: 'basicapp-85fbc.firebaseapp.com',
    storageBucket: 'basicapp-85fbc.firebasestorage.app',
    measurementId: 'G-KV94Y7L9YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPPD72stf6Uu5S1SnfR5wzzupP5XuSpvs',
    appId: '1:825501161515:android:1866744c800580b859f26e',
    messagingSenderId: '825501161515',
    projectId: 'basicapp-85fbc',
    storageBucket: 'basicapp-85fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJvqkpzdPM_eubLMqnzGf-YKBfHq0UVs',
    appId: '1:825501161515:ios:8791a42ded01727e59f26e',
    messagingSenderId: '825501161515',
    projectId: 'basicapp-85fbc',
    storageBucket: 'basicapp-85fbc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJvqkpzdPM_eubLMqnzGf-YKBfHq0UVs',
    appId: '1:825501161515:ios:8791a42ded01727e59f26e',
    messagingSenderId: '825501161515',
    projectId: 'basicapp-85fbc',
    storageBucket: 'basicapp-85fbc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEQZOvRWsbHfo0Ru2rgWk5I7jZKh0HxY',
    appId: '1:825501161515:web:0034f997a6cdc9eb59f26e',
    messagingSenderId: '825501161515',
    projectId: 'basicapp-85fbc',
    authDomain: 'basicapp-85fbc.firebaseapp.com',
    storageBucket: 'basicapp-85fbc.firebasestorage.app',
    measurementId: 'G-KJDSY1NZ8X',
  );
}
